<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\ArticleService' shared autowired service.

include_once $this->targetDirs[3].'/src/Services/ArticleService.php';

return $this->services['App\Services\ArticleService'] = new \App\Services\ArticleService();
