<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.yprcmff' shared service.

return $this->services['service_locator.yprcmff'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('articleService' => function () {
    $f = function (\App\Services\ArticleService $v = null) { return $v; }; return $f(${($_ = isset($this->services['App\Services\ArticleService']) ? $this->services['App\Services\ArticleService'] : $this->services['App\Services\ArticleService'] = new \App\Services\ArticleService()) && false ?: '_'});
}));
