<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDby3gpb\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDby3gpb/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDby3gpb.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDby3gpb\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDby3gpb\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Dby3gpb',
    'container.build_id' => '6aeb9ad1',
    'container.build_time' => 1541633843,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDby3gpb');
