<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTyp8zpn\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTyp8zpn/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTyp8zpn.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTyp8zpn\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTyp8zpn\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Typ8zpn',
    'container.build_id' => '6b176092',
    'container.build_time' => 1541454246,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTyp8zpn');
